spring:
  config:
    import: optional:file:.env.dev[.properties]
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  expiration-minutes: 1000

nginx:
  require-proxy: false

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jbdc:
            bind: TRACE
    com.ruialves.chirp: DEBUG